version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:80"
    networks:
      - sail
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/app/models/001-tables.sql:/docker-entrypoint-initdb.d/001-tables.sql # creates database's tables.
      - ./src/app/models/002-functions.sql:/docker-entrypoint-initdb.d/002-functions.sql # creates database's functions.
      - ./src/app/models/003-insert.sql:/docker-entrypoint-initdb.d/003-insert.sql
    networks:
      - sail

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - sail
    depends_on:
      - mysql

networks:
    sail:
        driver: bridge
volumes:
    mysql-data:
        driver: local
