<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Panel de administrador</h1>
            <form action="/logout">
                <button type="submit">Salir</button>
            </form>
        </header>
        <main>
            <?php if ($_SESSION['user_id'] == 1) : ?>
                <a href="/all-users">Administrar usuarios</a>
                <a href="/all-supervisors">Administrar supervisores</a>
                <a href="/all-products">Administrar productos</a>
            <?php elseif ($_SESSION['user_id'] == 2) : ?>
                <a href="/all-products">Administrar productos</a>
            <?php endif; ?>
        </main>
    </div>
</body>

</html>