<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Panel de administrador</h1>
        </header>
        <main>
            <a href="/all-users">Administrar usuarios</a>
            <a href="/all-supervisors">Administrar supervisores</a>
            <a href="/all-products">Administrar productos</a>
        </main>
    </div>
</body>

</html>