<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Productos</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Todos los productos</h1>
            <a href="/admin-panel">Atrás</a>
        </header>
        <main>
            <form class="create-product-form" action="/create-product" method="POST">
                <div>
                    <label for="name">Nombre producto</label>
                    <input id="name" type="text" name="name" />
                </div>
                <div>
                    <label for="price">Precio</label>
                    <input id="price" type="number" name="price" />
                </div>
                <div>
                    <label for="stock">Stock</label>
                    <input id="stock" type="number" name="stock" />
                </div>
                <div>
                    <label for="status">Status</label>
                    <input id="status" type="text" name="status" />
                </div>
                <button type="submit">Crear</button>
            </form>
            <section>
                <?php if (empty($products)) : ?>
                    <p>No hay usuarios registrados.</p>
                <?php else : ?>
                    <?php foreach ($products as $product) : ?>
                        <div class="user">
                            <section>
                                <img style="width:200px" src=<?= './assets/' . $product['name'] . '.jpeg' ?> alt="producto">
                                <div>
                                    <span>Nombre: <?= $product['name'] ?></span>
                                    <span>Precio: <?= $product['price'] ?></span>
                                    <span>Stock: <?= $product['stock'] ?></span>
                                    <span>Status: <?= $product['status'] ?></span>
                                </div>
                            </section>
                            <form action="/delete-product" method="POST">
                                <input type="hidden" name="id" value="<?= $product['id'] ?>" />
                                <button type="submit">Eliminar</button>
                            </form>
                            <form action="/set-product-status" method="POST">
                                <input type="hidden" name="id" value="<?= $product['id'] ?>" />
                                <?php if ($product['status'] == 'enabled') : ?>
                                    <input type="hidden" name="status" value="disabled" />
                                    <button type="submit">Deshabilitar</button>
                                <?php else : ?>
                                    <input type="hidden" name="status" value="enabled" />
                                    <button type="submit">Habilitar</button>
                                <?php endif; ?>
                            </form>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </section>
        </main>
    </div>
</body>

</html>