<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Perfil</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Actualizar Email</h1>
            <a href="/user-profile">Atrás</a>
        </header>
        <main>
            <form class="edit-email-form" action="/edit-email-data" method="POST">
                <div>
                    <label for="email">Nuevo email</label>
                    <input id="email" type="email" name="email" />
                </div>
                <button type="submit">Actualizar</button>
            </form>
        </main>
    </div>
</body>

</html>