<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Perfil</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Recuperar contraseña</h1>
            <a href="/login">Atrás</a>
        </header>
        <main>
            <form class="forgot-password-form" action="/forgot-password-data" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="text" name="email" />
                </div>
                <div>
                    <label for="new-password">Nueva contraseña</label>
                    <input id="new-password" type="password" name="new-password" />
                </div>
                <button type="submit">Recuperar</button>
            </form>
        </main>
    </div>
</body>

</html>