<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Iniciar sesion</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Login</h1>
        </header>
        <main>
            <form class="login-form" action="/login-data" method="POST">
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="email" name="email" />
                </div>
                <div>
                    <label for="password">Contraseña</label>
                    <input id="password" type="password" name="password" />
                </div>
                <button type="submit">Entrar</button>
            </form>
        </main>
    </div>
</body>

</html>