<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Iniciar sesion</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Login</h1>
        </header>
        <main>
            <form action="">
                <input type="email" name="email" />
                <input type="password" name="password" />
                <button type="submit">Entrar</button>
            </form>
        </main>
    </div>
</body>

</html>