<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./css/global.css">
    <title>Iniciar sesion</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Registrarse</h1>
        </header>
        <main>
            <form class="register-form" action="/register-data" method="POST">
                <input type="hidden" name="id" value=3 />
                <div>
                    <label for="username">Nombre de usuario</label>
                    <input id="username" type="text" name="username" />
                </div>
                <div>
                    <label for="phone">Telefono</label>
                    <input id="phone" type="text" name="phone" />
                </div>
                <div>
                    <label for="email">Email</label>
                    <input id="email" type="email" name="email" />
                </div>
                <div>
                    <label for="password">Contraseña</label>
                    <input id="password" type="password" name="password" />
                </div>
                <button type="submit">Registrarse</button>
            </form>
            <div>
                <a href="/login">Ya tienes cuenta? Inicia sesión</a>
            </div>
        </main>
    </div>
</body>

</html>