<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>
</head>

<body>
    <div class="container">
        <header>
            <h1>Informacion de usuario</h1>
        </header>
        <main>
            <section>
                <span>Foto</span>
                <button>Cambiar foto</button>
            </section>
            <section>
                <h3>Nombre de usuario</h3>
                <span>Admin</span>
            </section>
            <section>
                <h3>Telefono</h3>
                <span>12345</span>
            </section>
            <section>
                <h3>Email</h3>
                <span>admin@admin.com</span>
            </section>
            <section>
                <h3>Contraseña</h3>
                <a href="/edit-password">Cambiar contraseña</a>
            </section>
        </main>
    </div>
</body>

</html>